### ISSUE TITLE
iOS Safari errors

### ISSUE THREAD

**Issue by otheroom** [dwyl/range-touch#2]
I'm using range-touch in a project and it's been working great overall. I have however noticed some errors being reported when I do remove debugging in the iOS Simulator and iOS devices.

```
[Error] TypeError: 'undefined' is not an object (evaluating 'e.touches[0]')
```

In my code I've got a listener that updates a variable to track the actual element that's been clicked (or tapped).

``` javascript
var clickedElement;
document.addEventListener('mousedown', setClickElement);
document.addEventListener('touchmove', setClickElement);
setClickElement = function(e) {
    clickedElement = $(e.target);
};
```

The reported error occurs on Line 64: 

``` javascript
firstTouch = _isPointerType ? e : e.touches[0]
```

This doesn't seem to be causing and problems so far but I thought I'd report it. I'm not seeing this in desktop Safari or desktop Chrome.

**Comment by nelsonic** [comment]
Barry, thanks for submitting this issue.
So if I understand this correctly you are seeing the errors when you **_remove**_ debugging in iOS Simulator?

https://github.com/nelsonic/range-touch/blob/master/range-touch.js#L64

What version of (Mobile) Safari are you simulating?

**Comment by otheroom** [comment]
I see the error when I'm using the iOS Simulator with the desktop Safari Develop->iPad Simulator console running.

It's iOS Simulator 7.1 and Safari 7.0.6.

**Comment by nelsonic** [comment]
@otheroom any chance you can share a bit more code? (is your project open source?)
I'm having trouble reproducing it with my own mobile app. 
(thanks!)

**Comment by otheroom** [comment]
It's not an open source project so I can't share all the code but here are some more details that ought to help repro the issue:

Here are the other libs I'm including in the project:
- jQuery 2.1.1
- FastClick 1.0.3
- Handlebars 1.3.0

I'm using range-touch in forms that are using the range input type but the error is coming up on other pages. The code that I shared is intended to simply store the clicked element (typically a button) so that other code can do things like extract class or data attributes.

I'm seeing the error when I click in an open area of the page. I first noticed it on my login page when clicking on an area that has no elements, other than body. I should have included this bit of information in my initial report, sorry about that.

**Comment by otheroom** [comment]
The current version of range-touch does not generate these errors any longer.

**Comment by bakman2** [comment]
I still see this happening though. (the "current" version is the version from 2 year ago?)

**Comment by nelsonic** [comment]
Hi @bakman2 current version of what? the **range-touch** script has not changed since we wrote it.
the only change has been in JQuery. which version of JQuery are you using?
Also which version of IOS/Safari are you having issues with?  thanks.

**Comment by bakman2** [comment]
I am using 1.11.3. 
looking in the code; it searches for e.touches[0] which doesn't exist. 
e = 

```
Object:
altKey: false
bubbles: true
cancelable: true
ctrlKey: false
currentTarget: #document
data: undefined
delegateTarget: #document
eventPhase: 3
handleObj: Object
isDefaultPrevented: function ba() {return!1;}
jQuery1113010496568703092635: true
metaKey: false
originalEvent: TouchEvent
relatedTarget: undefined
shiftKey: false
target: input.colorrange
timeStamp: 1439279638356
type: "touchstart"
view: Window
which: 0
__proto__: Object

```

**Comment by bakman2** [comment]
btw; I am using dynamically added elements.

**Comment by nelsonic** [comment]
The dynamically added elements should not affect it. 
Which version of Safari/IOS are you using?
Is your code available on GitHub so we can try to replicate the issue?

**Comment by valerianka** [comment]
I started getting exact the same error on the same line. Sometimes it disappeares but most of the time it's there. I'm using iPhone simulator for testing, it's running iOS v.8.2(12D508) on iPhone 6, but I'm getting this error on all the devices(except on Mac). I created simple html file with range-type input, included the versions of jQuery that we use in the project and your file and as far as I can see the error is there. Try it: https://github.com/valerianka/test-range-touch-bug

**Comment by vovimayhem** [comment]
@bakman2 @valerianka Could it be that the version of Jquery your'e using is 1.7+? I'm using 2.1.4 and experiencing the exact same problem.

I noticed this:
- `e.touches` is undefined
- `e.originalEvent` is a `TouchEvent`
- `e.originalEvent.touches` exists, and is an object of type `TouchList`

I'm no jQuery expert, but I noticed this, and I think could be relatively simple to fix...

Forking out and giving it a try...

**Comment by nelsonic** [comment]
@vovimayhem Please keep us informed with your progress in getting this fixed we'd _gladly_ merge a PR if you can get it fixed. :+1:
