### ISSUE TITLE
Not on NPM yet

### ISSUE THREAD

**Issue by ootoovak** [dwyl/range-touch#4]
You have a `package.json` but I [can't find it on NPM](https://www.npmjs.com/search?q=range-touch). Will it be listed there?

**Comment by nelsonic** [comment]
@ootoovak _massive_ apologies for only replying now. (_I did not get a GitHub notification for this issue...!_)

Were you hoping to be able to `require('range-touch')` and use it in front-end code that gets `browserified` or `webpacked` ...?

**Comment by ootoovak** [comment]
@nelsonic no worries 😄 . Yeah, I'm pretty sure that was the use case I was going for. Looks like [it is on there](https://www.npmjs.com/package/range-touch) now so 👍 . Thanks!
