### ISSUE TITLE
Error in Chrome dev tools

### ISSUE THREAD

**Issue by vickybirtles** [dwyl/range-touch#6]
Hi guys, 
Great plugin! I'm finding that when in device mode in Chrome, I'm getting an error saying "range-touch.min.js:2 Uncaught TypeError: Cannot read property '0' of undefined" - it's also present on your demo. Have you any idea why this is? Or what the fix is? It happens any time I click anywhere.

**Comment by nelsonic** [comment]
@vickybirtles can you please send us a bit more detail:
- which version of chrome are you testing in
- what version of JQuery are you using?
- which device are you attempting to simulate?
- what OS?
  Thanks.

**Comment by vickybirtles** [comment]
Hi again, 
I'm using Chrome Version 49.0.2623.87 m
It happens once I choose to use their 'Device mode' in Developer Tools - any device/resolution emulation, clicking anywhere on the site will produce this issue each time.

I'm using Windows 7.

Thanks for any help you can offer!

![image](https://cloud.githubusercontent.com/assets/10464434/13873316/95dfad16-ece8-11e5-89bd-d2d4e19a97ae.png)

**Comment by nelsonic** [comment]
@vickybirtles apologies for late reply. 
can you please let us know which version of JQuery you are using?

**Comment by denydavy** [comment]
Hello!

I've encountered the same behavior. Moreover, the 'default'-skinned range input is not showing on simulated iphones (pretty much all of them).

I'm using jQuery 1.10.2 (link from your readme) & chrome 53.0.2785.101 (64-bit)

**Comment by denydavy** [comment]
Error is not happening with the latest jQuery 3.1.0

**Comment by nelsonic** [comment]
@denydavy thanks for letting us know. (_very much appreciated_!)

**Comment by denydavy** [comment]
The visibility of the default-skinned input is still not happening though

**Comment by nelsonic** [comment]
Latest Chrome. No Errors:
![image](https://user-images.githubusercontent.com/194400/32901053-c98c1f22-cae6-11e7-9a6d-bc5cb313ef2f.png)

@vickybirtles / @denydavy please re-open if you are still seeing this issue. thanks.
