### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rupl** [dwyl/range-touch#7]
I'd like to use this in an expat/MIT licensed project, but I didn't notice a license file in this repo. Can you confirm under what license this software is available?

**Comment by nelsonic** [comment]
@rupl good question! (_sorry that it's unclear..._) 
The license is listed as [`ISC`](https://opensource.org/licenses/ISC)  in the [`package.json#Line:23`](https://github.com/dwyl/range-touch/blob/1a95e4b5c4f5c609e1722877c6db3c0654446d1e/package.json#L23) but we can do a _much_ better job of making that clear for people.

**Comment by rupl** [comment]
Nice, thanks! Just a note about the license file itself. If you put it in a top-level file called `LICENSE` then Github will automatically display it alongside the commits/branches/releases/contributors tabs under Code view:

<img width="625" alt="screenshot of LICENSE displayed within GitHub interface" src="https://cloud.githubusercontent.com/assets/254753/19309444/19037f66-9085-11e6-8b16-8fc222f15887.png">

**Comment by nelsonic** [comment]
@rupl _even better_. 💡 
https://github.com/dwyl/range-touch/invitations you have write-access. go for it! 👍
